# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb59a51e3040bf2167bf4e5fe60ecd9e6b04c196256fda95e1865ec8f1a544ddc18af2ff7852ffda6021f7fbd12f87d4a106df9dfafa9de075eb3112ba009fcf

test:
  secret_key_base: 9ccc61f7bd87cade5f48d3a284bdca64818607a33139334340cfc583fa64b95c5edb7a156abe89c0011ef43a027c89b9bad6b63118c04d390f0c58e804b33e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
